import useAuth from '@/contexts/AuthContext';
import { getCookie } from '@/services/cookies';
import {
  Accordion,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
  Box, Button, HStack, Text, Image, Heading, ButtonGroup, Link, Stack
} from '@chakra-ui/react'
import { FaWhatsapp, FaFacebook, FaInstagram, FaTiktok } from 'react-icons/fa';

import Head from 'next/head';
import Slider from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Info from '../../components/InfoComponent';
import AccordionItemProps from '../../components/AcordionItem';
import { AddIcon, MinusIcon } from '@chakra-ui/icons';
import FooterJSX from '../../components/Footer';
import { useRouter } from 'next/router';


export default function Home() {

  const router = useRouter()

  const images = [
    // 'https://cdn.autopapo.com.br/box/uploads/2023/08/18150636/honda-atualiza-xre-300-para-a-li.png',
    // 'https://static.vakinha.com.br/uploads/vakinha/image/649035/WhatsApp_Image_2019-07-18_at_10.37.00.jpeg',
    'https://leao-leao-back.jx1fyp.easypanel.host/images/10knoPix.png',
    'https://leao-leao-back.jx1fyp.easypanel.host/images/10knoPix.png',
    'https://leao-leao-back.jx1fyp.easypanel.host/images/10knoPix.png',


    // 'https://bit.ly/dan-abramov'
  ];

  const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 3000
  };

  return (
    <Box>
      <Head>
        <title>Rifas do leão</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/*  */}
      <main style={{ maxWidth: '1420px', margin: '10', width: '100vw', justifyContent: 'center', height: -20 }}>
        <Box>
        <Box
        // backgroundColor={'gray'}
        // style={{ maxWidth: '1420px', margin: '10', width: '100vw',height: '65vh', justifyContent: 'center' }}
        >
          <Slider {...settings}>
            {images.map((image, index) => (
              <div key={index} style={{ display: 'flex', justifyContent: 'center' }}>
                <img src={image} alt={`Image ${index + 1}`} style={{ margin: 'auto' }} />
              </div>
            ))}
          </Slider>
          </Box>
          <Stack direction="column" spacing={4} alignItems="center">
            <Button
              onClick={() => router.push('/login')}
              size="lg"
              colorScheme="black"
              backgroundColor="black"
              color="white"
              fontWeight="700"
              textTransform="uppercase"
              letterSpacing="0.1px"
              mt={30}
              fontSize={25}
              textAlign="center"
              _hover={{ bg: 'gray.800' }}
            >
              Comprar
            </Button>
            <li>Fale com a gente </li>
            <Box display="flex" flexDirection="column-reverse">
              <ButtonGroup variant='outline' spacing='2'>
                <Link href="https://wa.me/5511965281517?text=ola%20Preciso%20de%20Suporte%20na%20Rifa" isExternal>
                  <Button leftIcon={<FaWhatsapp fontSize="30px" />} colorScheme='green'></Button>
                </Link>
                <Link href="https://www.facebook.com/profile.php?id=61555804864116&mibextid=ZbWKwL" isExternal>
                  <Button leftIcon={<FaFacebook fontSize="30px" />} colorScheme='blue'></Button>
                </Link>
                <Link href="https://www.instagram.com/rifas.leao?igsh=YmxnbWZ5ZTJpbmFx" isExternal>
                  <Button leftIcon={<FaInstagram fontSize="30px" />} colorScheme='pink'></Button>
                </Link>
                <Link href="https://www.tiktok.com/@rifasleao" isExternal>
                  <Button leftIcon={<FaTiktok fontSize="30px" />} colorScheme='white'></Button>
                </Link>
              </ButtonGroup>
          </Box>
          </Stack>

          {/* <Text fontSize='4xl' textAlign={'center'}>Ação do Leão</Text> */}
          {/* <Text fontSize='6xl' textAlign={'center'} mt={-10}>do</Text> */}
          {/* <Text fontSize='6xl' textAlign={'center'} mt={-10}>Leão</Text> */}
        </Box>
        {/* <Text  margin='auto' fontWeight={'500'} textAlign={'center'} w={{base: '80%', md:'20%'}}>Encontre, em poucos cliques, produtos que são verdadeiros tesouros.</Text> */}


        {/* <Box
      w={'100%'}
      mt={6}
      display={'flex'}
      justifyContent={'center'}
      >
        <Button 
        backgroundColor={'#f11f56'}
        color={'#fff'}
        w={{base: '50%', md:'20%'}}
        py={5.4}
        px={10}
        onClick={() => { router.push('/rifas') }}>
          Confira meus planos
        </Button>
      </Box>

      <Text 
      mt={10}
      fontSize='4xl'
      letterSpacing={'1px'}
      textAlign={'center'}>Não se assuste.</Text>
      <Text 
      mt={-5}
      fontSize='4xl'
      letterSpacing={'1px'}
      textAlign={'center'}>Sou um pirata do bem :)</Text>

      <Text
        fontWeight={'500'}
        w={{base: '80%', md:'40%'}}
        letterSpacing={'1px'}
        margin='auto'
        textAlign={'center'}
      >Use meus mapas (filtros) para achar os melhores tesouros (produtos) em segundos.</Text> */}

        {/* <Info title='Beba água limpa da fonte' description='Encontre antes os produtos que todos estão procurando e lucre com eles tudo que há pra lucrar.'/>
      <Info alternate={false} title='Vá pelos meus atalhos exclusivos' description='O que seus concorrentes demoram várias horas para encontrar, vou te entregar em alguns minutos.'/>
      <Info button={true} title='Sem mim, seu negócio é um barco à deriva' description='Sem saber quais produtos vender, seu negócio fica sem rumo e pode estar indo para o buraco, e você só saberá depois de cair nele.'/>

      <Text mt={10} textAlign={'center'} fontSize='4xl'>Perguntas frequentes</Text>

      <Box 
      mt={10}
      display={'flex'}
      justifyContent={'end'}
      flexDirection={'row'}
      >
            <Box
            display={{base: 'none', md: 'block'}}
            p={1}
            height={'460px'}
            width={'20%'}
          >
            <Image
            borderRadius={10}
              src="https://th.bing.com/th/id/OIP.q86T2esYe207gNMd1kBE_gHaE6?pid=ImgDet&rs=1"
              alt="Imagem"
              objectFit="cover"
              height="100%"
              width="100%"
            />
          </Box>

      <Accordion allowMultiple width={'100%'}  >

        <AccordionItemProps title='O que vou receber?' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />
        <AccordionItemProps title='Qual a forma de pagamento?' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />
        <AccordionItemProps title='Terei suporte para utilizar a plataforma?' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />
        <AccordionItemProps title='Quais horários posso utilizar a ferramenta?' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />
        <AccordionItemProps title='Não consigo fazer de graça na plataforma o que farei aqui? ' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />
        <AccordionItemProps title='Tenho que usar meus dados de acesso das plataformas para usar a Affiliate Pirate?' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />
        <AccordionItemProps title='Depois que eu escolher um produto, poderei me afiliar à ele dentro das plataformas?' description='Você vai obter acesso à ferramenta Affiliate Pirate para encontrar produtos campeões nas principais plataformas de afiliados.' />

      </Accordion>
      </Box> */}
      </main>

    </Box>
  )
}

export async function getServerSideProps(context) {
  const token = getCookie("token", context.req);
  // const cookieValue = getCookie(context.req, 'nomeDoCookie'); // Substitua 'nomeDoCookie' pelo nome do seu cookie
  if (token) {

    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    }
  }
  return {
    props: {
    },
  };
}
