import useAuth from "@/contexts/AuthContext";
import { getCookie } from "@/services/cookies";
import {
  Accordion,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
  Box,
  Button,
  HStack,
  Text,
  Image,
  Heading,
  ButtonGroup,
  Stack,
  RadioGroup,
  InputGroup,
  InputLeftElement,
  Input,
  Spacer,
} from "@chakra-ui/react";
import Head from "next/head";

import Info from "../../components/InfoComponent";
import AccordionItemProps from "../../components/AcordionItem";
import {
  AddIcon,
  MinusIcon,
  PhoneIcon,
  WarningTwoIcon,
} from "@chakra-ui/icons";
import FooterJSX from "../../components/Footer";
import RadioPlans from "../../components/RadioPlans";
import { useRouter } from "next/router";
import SegmentedControl from "../../components/SegmentControl";
import { useRef, useState } from "react";
import { AiFillCheckCircle } from "react-icons/ai";
import Images from 'next/image'


export default function Home() {
  const [recoverdPassword, setRecoverdPassword] = useState(false);
  const [passwordChanged, setPasswordChanged] = useState(false);
  const router = useRouter();

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box width={"100%"} height={"50vh"} backgroundColor={"#c2c2c2"}>
      <Box
        w={'100%'}
        justifyContent={'space-around'}
        display={'flex'}
        flexDirection={'row'}
        >
          {/* <Image src={require('../.')} /> */}

          {/* <Box 
          >
          <Images
              style={{
                padding: 10
              }}
              width={150}
              src={require('../../public/white-logo.png')}
            />
          </Box> */}
          
          <Box 
          p={10}
          display={'flex'}
          justifyContent={'center'}
          alignItems={'center'}
          >
            <Text 
            color={'#fff'}
            mr={{base: 1,md:10}}>Lembrou a senha?</Text>
            <Spacer />
            <Button
            onClick={() => router.push('/login')}
            borderColor={'#fff'}
            variant={'outline'}
            color={'#fff'}
            >Entrar</Button>
          </Box>
        </Box>


      </Box>

      <Box width={"100%"} height={"50vh"} backgroundColor={"#ffff"}></Box>

      <main style={{ maxWidth: "1420px", margin: "auto" }}>
        <Box
          mt={10}
          mb={10}
          display={"flex"}
          width={"100%"}
          position={"absolute"}
          top={"25vh"}
          left={"0vw"}
          flexDirection={"column"}
        >
          <Box
            border={"2px solid #c2c2c2"}
            borderRadius={"5px"}
            m={"auto"}
            maxW={"1420px"}
            minW={{base: 300, md: 400}}
            maxWidth={600}
            p={5}
            backgroundColor={"#fff"}
            display={"flex"}
            flexDirection={"column"}
            alignItems={"center"}
          >
        {!passwordChanged ? (
            
            <>
            {!recoverdPassword ? (
              <>
                <Text
                  fontSize="xl"
                  textAlign={"center"}
                  fontWeight={"600"}
                  letterSpacing={"0.5px"}
                >
                  Esqueceu a senha?
                </Text>

                <Box
                  p={0.5}
                  w={280}
                  fontWeight={"600"}
                  color={"#545454"}
                  fontSize={"12px"}
                  display={"flex"}
                  alignItems={"center"}
                  borderRadius={"3px"}
                >
                  <Text>
                    Não se preocupe. Enviaremos a você por e-mail as instruções
                    para redefinir sua senha.
                  </Text>
                </Box>

                <Stack p={5} w={"100%"} spacing={5}>
                  <Box>
                    <Text fontWeight={"semibold"} letterSpacing={"0.5px"}>
                      E-mail da conta{" "}
                    </Text>
                    <Input
                      p={2}
                      borderRadius={"5px"}
                      width={"100%"}
                      size="sm"
                      fontWeight={"semibold"}
                      sx={{
                        _placeholder: {
                          color: "#c2c2c2",
                          fontWeight: "500",
                        },
                      }}
                      type="tel"
                      placeholder="Qual o e-mail da conta?"
                    />
                    <Text color={"red"} fontSize={"2xs"}>
                      Por favor, digite um email válido.
                    </Text>
                  </Box>

                  <Button
                    backgroundColor={"#000"}
                    _hover={{ backgroundColor: "#000" }}
                    color={"#fff"}
                    onClick={() => setRecoverdPassword(true)}
                  >
                    Recuperar senha
                  </Button>
                </Stack>
              </>
            ): (
            <>
                {/* PARTE DE RECUPERAÇÃO COM EMAIL ENCONTRADO */}

                <Text
                  fontSize="xl"
                  textAlign={"center"}
                  fontWeight={"600"}
                  letterSpacing={"0.5px"}
                >
                  Alterar a senha
                </Text>

                <Box
                  p={0.5}
                  w={280}
                  fontWeight={"600"}
                  color={"#545454"}
                  fontSize={"12px"}
                  display={"flex"}
                  alignItems={"center"}
                  borderRadius={"3px"}
                >
                  <Text>
                  Informe uma nova senha para acessar a sua conta.
                  </Text>
                </Box>

                <Stack p={5} w={"100%"} spacing={5}>
                  <Box>
                    <Text fontWeight={"semibold"} letterSpacing={"0.5px"}>
                    Nova senha
                    </Text>
                    <Input
                      p={2}
                      borderRadius={"5px"}
                      width={"100%"}
                      size="sm"
                      fontWeight={"semibold"}
                      sx={{
                        _placeholder: {
                          color: "#c2c2c2",
                          fontWeight: "500",
                        },
                      }}
                      type="tel"
                      placeholder="Digite sua nova senha"
                    />
                    <Text color={"red"} fontSize={"2xs"}>
                      Por favor, digite uma senha válida.
                    </Text>
                  </Box>


                  <Box>
                    <Text fontWeight={"semibold"} letterSpacing={"0.5px"}>
                    Repita a nova senha
                    </Text>
                    <Input
                      p={2}
                      borderRadius={"5px"}
                      width={"100%"}
                      size="sm"
                      fontWeight={"semibold"}
                      sx={{
                        _placeholder: {
                          color: "#c2c2c2",
                          fontWeight: "500",
                        },
                      }}
                      type="tel"
                      placeholder="Digite sua nova senha"
                    />
                    <Text color={"red"} fontSize={"2xs"}>
                      Por favor, tente corrigir a senha digitada.
                    </Text>
                  </Box>


                  <Button
                    backgroundColor={"#000"}
                    _hover={{ backgroundColor: "#000" }}
                    color={"#fff"}
                    onClick={() => setPasswordChanged(true)}
                  >
                    Alterar senha
                  </Button>
                </Stack>
              </>
            )}
            </>
            ): (
                <>
                {/* PARTE DE RECUPERAÇÃO CONCLUIDA */}
                

                <AiFillCheckCircle size={50} color={"#c2c2c2"} />
                <Text
                  fontSize="xl"
                  textAlign={"center"}
                  fontWeight={"600"}
                  letterSpacing={"0.5px"}
                >
                  Prontinho!
                </Text>

                
                  <Text
                  fontWeight={"600"}
                  color={"#545454"}
                  fontSize={"12px"}
                  >
                  Sua senha foi alterada com sucesso.
                  </Text>

                <Stack p={5} w={"100%"} spacing={5}>
                  <Button
                    backgroundColor={"#000"}
                    _hover={{ backgroundColor: "#000" }}
                    color={"#fff"}
                    onClick={() => router.push("/login")}
                  >
                    Voltar para o login
                  </Button>
                </Stack>
                </>
            )}
          </Box>
        </Box>
      </main>
    </Box>
  );
}

export async function getServerSideProps(context) {
  const token = getCookie("token", context.req);

  if (token) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
}
